### ISSUE TITLE
Keyboard shortcut does not remain in the status bar

### ISSUE THREAD

**Issue by gep13** [madskristensen/ShowTheShortcut#1]
### Installed product versions
- Visual Studio 2015 Enterprise
- ShowTheShortcut 1.1.8

### Description
Keyboard shortcut does not remain in the status bar.  See image below:

![showtheshortcut](https://cloud.githubusercontent.com/assets/1271146/14630519/1172a2a4-0606-11e6-8cde-e89ed0b4a469.gif)

### Steps to recreate
1. Installed the extension
1. Open solution
1. Open Tools | Options and enabled the "Show on shortcut" setting and ensured timeout is set to 0
1. Executed manual menu based operation - Edit | Find and Replace | Quick Find
1. Briefly see shortcut shown in the status bar, but it goes away immediately

### Current behavior
The keyboard shortcut appears briefly in the status bar, but then immediately goes away.  I can see the keyboard shortcut output to the output window though.

### Expected behavior
Based on the timeout setting of 0, I would expect that the shortcut be shown in the status bar until the next shortcut is activated.

**Comment by scccboom** [comment]
## Installed product versions

- Visual Studio: 2019 Professional 161.1.5
- This extension: 1.4.47

## Description

There are no shortcuts in the status bar log. 
Set the "Show tool tip" to true, and it doesn't work.
