### ISSUE TITLE
Console window is overflooded by "Debug.StartupProjects (no shortcut)" when solution is load

### ISSUE THREAD

**Issue by TobiasSekan** [madskristensen/ShowTheShortcut#14]
### Installed product versions
- Visual Studio: 2017 Preview Version 15.9.0 Preview 3.0
- This extension: 1.4.35

### Description
The log Window log many of `Debug.StartupProjects (no shortcut)` after a solution is load

### Steps to recreate
1. Start Visual Studio
2. Open a solution
3. Look into the debug window of "Learn the shortcut"
4. Wait a few seconds

### Current behavior
![bla](https://user-images.githubusercontent.com/17874713/46849544-39c72e00-cdf0-11e8-99b4-223e64487c89.png)

**Comment by VladSnap** [comment]
Similar problem!
Reproduced in a large solution. (100+ projects)

Visual Studio: 2017 Version 15.8.7
This extension: 1.4.35

**Comment by cfenwick74** [comment]
This happens to me too. As a workaround, I changed set the value of `Log commands without shortcut` to `false` in the options. (Tools > Options > Keyboard > Shortcuts)

**Comment by mscreations** [comment]
I have had this as well. It also caused devenv to throw an exception, but I wasn't able to capture any of the exception details. I'm going to try @cfenwick74 's solution and see if that helps at all.

Visual Studio 2019 Community Preview 5.0 16.6.0

**Comment by markolbert** [comment]
I'm running into this in VS2019 16.7.1 with a solution having 8 C# projects.
