### ISSUE TITLE
Only compatible with Professional Edition?

### ISSUE THREAD

**Issue by iamhammer** [madskristensen/ShowTheShortcut#18]
### Installed product versions
- Visual Studio : 2019 Community Edition
- This extension: 1.4.35

### Description
I was looking to install this extension on a hobby machine, but the VSIX installer cancels and reports **"This extension is not installable on any currently installed products."**

Relevant snippets from the install log:
```

Supported Products : 
	Microsoft.VisualStudio.Pro
		Version : [14.0]
	Microsoft.VisualStudio.Pro
		Version : [15.0]
	Microsoft.VisualStudio.Pro
		Version : [16.0]
Searching for applicable products...
Found installed product - Visual Studio Community 2019
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
```
Is there something that the Community edition is lacking that would prevent this extension from being applicable?
Thanks!

**Comment by Gerboa** [comment]
Also can't be installed in VisualStudio Enterprise.

**Comment by RudeySH** [comment]
I can also confirm this extension can't be installed on VS2019 Community (v16.3.2)

**Comment by iamhammer** [comment]
Nor will it install in 2019 Pro.

**Comment by michaelm7456** [comment]
I've had a look into this one and confirmed the latest iteration of this Extension on VS gallery is indeed working with other versions of Visual Studio 2019.

I had raised a Pull Request to fix this, but it seems there was a [commit](https://github.com/madskristensen/ShowTheShortcut/commit/b2a1b207e33683e1ed83a37303ee7ace6a4ed327) in Dec '19 which extended the Visual Studio range on permitted VS Versions for this Extension and fixed the issue.

The last publish was 29th June 2020, which includes this fix.
![image](https://user-images.githubusercontent.com/20442719/88426048-5c211480-cde8-11ea-93cb-1a3705b25db2.png)

There's the full confirmation [here](https://github.com/madskristensen/ShowTheShortcut/pull/20#issuecomment-663681342), but if you download the latest version from the VS Gallery it should be ok now.

Hope this helps!

**Comment by madskristensen** [comment]
@michaelm7456 Thank you so much for confirming. Much appreciated!! 

I'll go ahead and close the issue
