### ISSUE TITLE
Error while visual studio starts.

### ISSUE THREAD

**Issue by babula38** [madskristensen/ShowTheShortcut#19]
### Installed product versions
- Visual Studio: vs2019 community preview
- This extension: Learn the Shortcut

### Description
Error loading the plug in 

### Steps to recreate
- install the extension.
- restart visualstudio

### Current behavior
- Gives error while visual studio starts.

### Expected behavior
- Vs2019 should not show the error message.

![shout cut key error](https://user-images.githubusercontent.com/4153708/82724422-b96aed80-9cf3-11ea-8b94-68a9837fb743.jpg)

**Comment by mrlacey** [comment]
I had a similar experience. 
Here's the entry from the log

```xml
  <entry>
    <record>2987</record>
    <time>2020/06/09 17:04:33.407</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VSPackage]Source: &apos;ShowTheShortcut&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at ShowTheShortcut.StatusBarInjector.FindStatusBar() in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 56&#x000D;&#x000A;   at ShowTheShortcut.StatusBarInjector..ctor(Window pWindow) in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 21&#x000D;&#x000A;   at ShowTheShortcut.CommandHandler..ctor(DTE2 dte, Options options) in C:\projects\showtheshortcut\src\CommandHandler.cs:line 24&#x000D;&#x000A;   at ShowTheShortcut.CommandHandler.&lt;InitializeAsync&gt;d__15.MoveNext() in C:\projects\showtheshortcut\src\CommandHandler.cs:line 95&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at ShowTheShortcut.VSPackage.&lt;InitializeAsync&gt;d__0.MoveNext() in C:\projects\showtheshortcut\src\VSPackage.cs:line 26&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()</description>
    <guid>{9DA28329-F9D5-4F18-91C3-D3285B103D1A}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by rs38** [comment]
same here:

`SetSite failed for package [VSPackage]Source: 'ShowTheShortcut' Description: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.at ShowTheShortcut.StatusBarInjector.FindStatusBar() in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 56at ShowTheShortcut.StatusBarInjector..ctor(Window pWindow) in C:\projects\showtheshortcut\src\StatusbarInjector.cs:line 21at ShowTheShortcut.CommandHandler..ctor(DTE2 dte, Options options) in C:\projects\showtheshortcut\src\CommandHandler.cs:line 24at ShowTheShortcut.CommandHandler.d__15.MoveNext() in C:\projects\showtheshortcut\src\CommandHandler.cs:line 95 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at ShowTheShortcut.VSPackage.d__0.MoveNext() in C:\projects\showtheshortcut\src\VSPackage.cs:line 26 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.VisualStudio.Shell.AsyncPackage.c__DisplayClass20_0.<b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)at Microsoft.VisualStudio.Threading.JoinableTask.d__68.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)at Microsoft.VisualStudio.Services.VsTask.GetResult()`

**Comment by drpeck** [comment]
Exactly the same here using VS 2019 Community Edition. I installed this via the 'Basic Essentials' extension, which may or may not be related.

**Comment by madskristensen** [comment]
This should now be fixed and an update is currently being uploaded and validated on the Marketplace. Should be ready in 5 minutes

**Comment by drpeck** [comment]
Top man! Thank you

**Comment by babula38** [comment]
> This should now be fixed and an update is currently being uploaded and validated on the Marketplace. Should be ready in 5 minutes

thanks it is working now
