### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [madskristensen/ShowTheShortcut#23]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by arphox** [comment]
@madskristensen tagging for attention, can you give us some info on this, please?

**Comment by madskristensen** [comment]
Yeah, it's on my todo list

**Comment by kirbatious** [comment]
But Mads, how long is your todo list?! :)

I found this really useful, but I guess as a toy project this isn't something you can dump on a junior dev at MS?

Thanks anyway!

**Comment by hymccord** [comment]
@kirbatious The thing about OSS, is that it sometimes needs support from the community. Nothing stopped me from submitting a PR to close this issue!
